"""图像画面扩展（扩图）工具包数据模型（pydantic）。

字段统一用 snake_case；扩图参数对应百炼 ``parameters`` 字段，全部可选，
未设置（None）则不传给百炼，由百炼按默认值处理。
"""

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class TaskStatus(StrEnum):
    """扩图任务状态（百炼任务状态枚举）。"""

    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELED = "CANCELED"
    UNKNOWN = "UNKNOWN"


class OutpaintingParameters(BaseModel):
    """扩图参数（全部模式，均可选）。

    四类扩展参数按百炼优先级生效：output_ratio > x_scale/y_scale > offset；
    angle 先旋转后扩展。详见 https://help.aliyun.com/zh/model-studio/image-scaling-api
    """

    model_config = ConfigDict(extra="forbid")

    angle: int | None = Field(None, ge=0, le=359)  # 逆时针旋转角度（度）
    output_ratio: Literal["", "1:1", "3:4", "4:3", "9:16", "16:9"] | None = None  # 输出宽高比
    x_scale: float | None = Field(None, ge=1.0, le=3.0)  # 水平方向按比例扩展
    y_scale: float | None = Field(None, ge=1.0, le=3.0)  # 垂直方向按比例扩展
    top_offset: int | None = Field(None, ge=0)  # 上方添加像素
    bottom_offset: int | None = Field(None, ge=0)  # 下方添加像素
    left_offset: int | None = Field(None, ge=0)  # 左侧添加像素
    right_offset: int | None = Field(None, ge=0)  # 右侧添加像素
    best_quality: bool | None = None  # 最佳质量模式（耗时成倍增加）
    limit_image_size: bool | None = None  # 限制输出文件大小
    add_watermark: bool | None = None  # 添加 "Generated by AI" 水印

    def to_request_params(self) -> dict:
        """转成发给百炼的 ``parameters`` 字典（剔除 None 字段）。"""
        return self.model_dump(exclude_none=True)


class CreateTaskResponse(BaseModel):
    """创建扩图任务响应。"""

    task_id: str
    task_status: str


class QueryTaskResponse(BaseModel):
    """查询扩图任务响应。"""

    task_id: str
    task_status: str  # TaskStatus 值
    output_image_url: str | None = None  # 成功时返回的结果图 URL
    code: str | None = None  # 失败时的错误码（供前端展示）
    message: str | None = None  # 失败时的错误信息
