"""图片模块：新建 pictures 表

Revision ID: c63446b89172
Revises: 44c893efd0a2
Create Date: 2026-08-13 16:33:52.857233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c63446b89172'
down_revision: Union[str, Sequence[str], None] = '44c893efd0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pictures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('introduction', sa.String(length=512), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('pic_size', sa.BigInteger(), nullable=True),
    sa.Column('pic_width', sa.Integer(), nullable=True),
    sa.Column('pic_height', sa.Integer(), nullable=True),
    sa.Column('pic_scale', sa.Float(), nullable=True),
    sa.Column('pic_format', sa.String(length=32), nullable=True),
    sa.Column('color_mode', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_pictures_category'), 'pictures', ['category'], unique=False)
    op.create_index(op.f('ix_pictures_introduction'), 'pictures', ['introduction'], unique=False)
    op.create_index(op.f('ix_pictures_name'), 'pictures', ['name'], unique=False)
    op.create_index(op.f('ix_pictures_status'), 'pictures', ['status'], unique=False)
    op.create_index(op.f('ix_pictures_user_id'), 'pictures', ['user_id'], unique=False)
    # 注：tags 为 JSON 列，PostgreSQL 不支持 btree 索引，故不建索引（搜索用 cast(tags as text) ILIKE）
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pictures_user_id'), table_name='pictures')
    op.drop_index(op.f('ix_pictures_status'), table_name='pictures')
    op.drop_index(op.f('ix_pictures_name'), table_name='pictures')
    op.drop_index(op.f('ix_pictures_introduction'), table_name='pictures')
    op.drop_index(op.f('ix_pictures_category'), table_name='pictures')
    op.drop_table('pictures')
    # ### end Alembic commands ###
